// Galactic Dominion — Economy and Resources research branch.
// Tier/node numbering follows the design brief: T1 N1 through T8 N1.
const u = (name) => ({ upgrades: [name] });

export const ECONOMY_TECH_TREE = [
  { id: 'mining_resource_generation', name: 'Mining and Resource Generation', description: 'Establishes the empire’s foundational mining and energy-generation infrastructure.', category: 'Economy and Resources', tier: 1, researchTurns: 1, prerequisites: [], isPrimary: true, unlocks: { upgrades: ['Planet Mining I', 'Planet Mining II', 'Planet Mining III', 'Solar Energy Farm I', 'Solar Energy Farm II'] } },

  { id: 'sub_surface_mining', name: 'Sub Surface Mining', description: 'Pushes extraction below the planetary crust into richer mineral seams.', category: 'Economy and Resources', tier: 2, researchTurns: 2, prerequisites: ['mining_resource_generation'], unlocks: { upgrades: ['Core Mining I', 'Core Mining II', 'Core Mining III', 'Core Mining IV'] } },
  { id: 'energy_collection_grid', name: 'Energy Collection Grid', description: 'Builds a coordinated planetary grid for harvesting and distributing solar energy.', category: 'Economy and Resources', tier: 2, researchTurns: 2, prerequisites: ['mining_resource_generation'], unlocks: u('ADV ENERGY COLLECTION I') },
  { id: 'orbit_mining', name: 'Orbit Mining', description: 'Moves industrial extraction into stable orbital operations.', category: 'Economy and Resources', tier: 2, researchTurns: 2, prerequisites: ['mining_resource_generation'], unlocks: { upgrades: ['Orbital Miners I', 'Orbital Miners II'] } },

  { id: 'deep_core_extraction', name: 'Deep Core Extraction', description: 'Reaches deep planetary reserves through advanced extraction systems.', category: 'Economy and Resources', tier: 3, researchTurns: 3, prerequisites: ['sub_surface_mining'], unlocks: { upgrades: ['Deep Core Syphon I', 'Deep Core Syphon II', 'Deep Core Syphon III'] } },
  { id: 'planetary_solar_harness', name: 'Planetary Solar Harness', description: 'Expands planetary solar collection into high-output energy infrastructure.', category: 'Economy and Resources', tier: 3, researchTurns: 3, prerequisites: ['energy_collection_grid'], unlocks: u('ADV ENERGY COLLECTION II') },
  { id: 'intra_system_automated_mining', name: 'Intra System automated Mining', description: 'Automates mining fleets throughout the home star system.', category: 'Economy and Resources', tier: 3, researchTurns: 3, prerequisites: ['orbit_mining'], unlocks: u('Orbital Miners III') },

  { id: 'tectonic_shaft_mining', name: 'Tectonic Shaft Mining', description: 'Exploits tectonic structures to dramatically expand Ferrite and Berentium extraction and introduces Aetherium Crystal production.', category: 'Economy and Resources', tier: 4, researchTurns: 4, prerequisites: ['deep_core_extraction'], isPrimary: true },
  { id: 'thermal_core_fracturing', name: 'Thermal Core Fracturing', description: 'Fractures superheated planetary cores to expose additional strategic resources.', category: 'Economy and Resources', tier: 4, researchTurns: 4, prerequisites: ['deep_core_extraction'] },
  { id: 'orbit_solar_reflector', name: 'Orbit Solar Reflector', description: 'Uses orbital reflector arrays to concentrate stellar energy into collection networks.', category: 'Economy and Resources', tier: 4, researchTurns: 4, prerequisites: ['planetary_solar_harness'], unlocks: u('ADV ENERGY COLLECTION III') },
  { id: 'intra_system_freighter_capacity', name: 'Intra System Freighter Capacity', description: 'Increases the cargo capacity of automated system-mining logistics.', category: 'Economy and Resources', tier: 4, researchTurns: 4, prerequisites: ['intra_system_automated_mining'], unlocks: u('System Miners II') },

  { id: 'magma_seam_extraction', name: 'Magma Seam Extraction', description: 'Extracts resources directly from deep planetary magma seams.', category: 'Economy and Resources', tier: 5, researchTurns: 5, prerequisites: ['tectonic_shaft_mining', 'thermal_core_fracturing'], isPrimary: true },
  { id: 'core_plasma_excavation', name: 'Core Plasma Excavation', description: 'Uses plasma excavation to harvest large quantities of strategic material and Aetherium from extreme environments.', category: 'Economy and Resources', tier: 5, researchTurns: 5, prerequisites: ['magma_seam_extraction'], unlocks: { upgrades: ['Plasma Extraction I', 'Plasma Extraction II'] } },
  { id: 'orbital_energy_relay', name: 'Orbital Energy Relay', description: 'Links orbital energy collectors into a high-output relay network.', category: 'Economy and Resources', tier: 5, researchTurns: 5, prerequisites: ['orbit_solar_reflector'], unlocks: u('ADV ENERGY CONNECTION IV') },
  { id: 'orbit_cargo_rails', name: 'Orbit Cargo Rails', description: 'Creates high-throughput orbital cargo routes for Ferrite and Berentium.', category: 'Economy and Resources', tier: 5, researchTurns: 5, prerequisites: ['intra_system_freighter_capacity'], unlocks: u('Cargo Rails I') },
  { id: 'asteroid_harpooning', name: 'Asteroid Harpooning', description: 'Captures resource-rich asteroids for controlled orbital extraction.', category: 'Economy and Resources', tier: 5, researchTurns: 5, prerequisites: ['intra_system_freighter_capacity'], unlocks: u('Asteroid Hostler') },
  { id: 'orbital_slag_production', name: 'Orbital Slag Production', description: 'Processes orbital debris and industrial slag into additional usable resources.', category: 'Economy and Resources', tier: 5, researchTurns: 5, prerequisites: ['orbit_cargo_rails', 'asteroid_harpooning'], unlocks: { upgrades: ['Debris Scoop I', 'Debris Scoop II'] } },

  { id: 'gravimetric_core_harvesting', name: 'Gravimetric Core Harvesting', description: 'Uses controlled gravity fields to harvest matter from extreme planetary cores.', category: 'Economy and Resources', tier: 6, researchTurns: 6, prerequisites: ['magma_seam_extraction', 'core_plasma_excavation'], unlocks: { upgrades: ['Gravity Furnace I', 'Gravity Furnace II'] } },
  { id: 'atmosphere_ion_harvesting', name: 'Atmosphere Ion Harvesting', description: 'Harvests charged atmospheric particles for additional energy generation.', category: 'Economy and Resources', tier: 6, researchTurns: 6, prerequisites: ['orbital_energy_relay'], unlocks: u('ADV ENERGY COLLECTION V') },
  { id: 'mass_driver_sling', name: 'Mass Driver Sling', description: 'Accelerates bulk mining payloads between planetary and orbital facilities.', category: 'Economy and Resources', tier: 6, researchTurns: 6, prerequisites: ['orbit_cargo_rails', 'asteroid_harpooning'], unlocks: { upgrades: ['Advanced Sling Mining I', 'Advanced Sling Mining II'] } },
  { id: 'laser_ablation_mining', name: 'Laser Ablation Mining', description: 'Uses industrial lasers to vaporize and recover high-value mineral deposits.', category: 'Economy and Resources', tier: 6, researchTurns: 6, prerequisites: ['magma_seam_extraction', 'orbital_slag_production'], unlocks: u('Laser Ablator I') },
  { id: 'zero_g_centrifugal_refinery', name: 'Zero-G Centrifugal Refinery', description: 'Separates Ferrite into higher-value Berentium in zero-gravity refineries.', category: 'Economy and Resources', tier: 6, researchTurns: 6, prerequisites: ['core_plasma_excavation', 'orbital_slag_production'], unlocks: u('Zero G Refinery I') },

  { id: 'stellar_corona_skimming', name: 'Stellar Corona Skimming', description: 'Skims stellar coronae to create Aetherium from immense energy reserves.', category: 'Economy and Resources', tier: 7, researchTurns: 7, prerequisites: ['atmosphere_ion_harvesting', 'zero_g_centrifugal_refinery'], unlocks: u('Solar Energy Conversion I') },
  { id: 'zero_point_extraction', name: 'Zero-Point Extraction', description: 'Extracts energy directly from quantum vacuum fluctuations.', category: 'Economy and Resources', tier: 7, researchTurns: 7, prerequisites: ['gravimetric_core_harvesting', 'atmosphere_ion_harvesting'], unlocks: u('ADV ENERGY COLLECTION VI') },

  { id: 'dyson_sphere', name: 'Dyson Sphere', description: 'The ultimate industrial megastructure: surrounds a star and multiplies imperial resource collection on a galactic scale.', category: 'Economy and Resources', tier: 8, researchTurns: 8, prerequisites: ['stellar_corona_skimming', 'zero_point_extraction'], isPrimary: true },
];

export const ECONOMY_TECH_IDS = new Set(ECONOMY_TECH_TREE.map((t) => t.id));