// Empire-wide upgrade definitions.
// Each Roman-numeral upgrade is a distinct one-time purchase unlocked by research.
const makeUpgrade = (name, description, gatingTechId, effectLabel, bonus, cost = { aetherium_crystal: 300, ferrite_titanium: 600, vrind: 800 }) => ({ id: name.toLowerCase().replace(/[^a-z0-9]+/g, "_"), name, description, gatingTechId, effectLabel, bonus, cost, maxLevel: 1 });

export const EMPIRE_UPGRADES = [
  makeUpgrade("Population Growth I", "Increases empire population growth.", "centralized_administration", "Population Growth", 0.05),
  makeUpgrade("Population Growth II", "Further increases empire population growth.", "planetary_growth_matrix", "Population Growth", 0.05),
  makeUpgrade("Population Growth III", "Further increases empire population growth.", "imperial_networking", "Population Growth", 0.05),
  makeUpgrade("Income Upgrade I", "Strictly increases recurring VRIND income.", "centralized_administration", "VRIND Income", 0.05),
  makeUpgrade("Income Upgrade II", "Strictly increases recurring VRIND income.", "tachyon_communications", "VRIND Income", 0.05),
  makeUpgrade("Income Upgrade III", "Strictly increases recurring VRIND income.", "imperial_directives", "VRIND Income", 0.05),
  makeUpgrade("Resource Finder I", "Increases resources found during exploration.", "aero_probe_launcher", "Resources Found", 0.05),
  makeUpgrade("Resource Finder II", "Further increases resources found during exploration.", "deep_space_survey_probe", "Resources Found", 0.10),
  makeUpgrade("Resource Finder III", "Further increases resources found during exploration.", "atmospheric_hazard_cartography", "Resources Found", 0.15),
  makeUpgrade("Cost Reducer I", "Reduces Exploration Ship energy cost by 5%.", "sub_light_mapping", "Exploration Energy Cost", -0.05),
  makeUpgrade("Cost Reducer II", "Reduces Exploration Ship energy cost by 10%.", "anomaly_analysis_algorithms", "Exploration Energy Cost", -0.10),
  makeUpgrade("Exploration Speed I", "Makes exploration 5% faster.", "long_range_sensors", "Exploration Time", -0.05),
  makeUpgrade("Exploration Speed II", "Makes exploration 10% faster.", "tachyon_sensor_array", "Exploration Time", -0.10),
  makeUpgrade("Exploration Speed III", "Makes exploration 15% faster.", "warp_lane_optimization", "Exploration Time", -0.15),
  makeUpgrade("Exploration Speed IV", "Makes exploration 20% faster.", "fold_navigation", "Exploration Time", -0.20),
  makeUpgrade("ECM Field Matrix I", "Provides 33% planetary ECM detection capability.", "advanced_detection_grid", "ECM Detection", 0.33),
  makeUpgrade("ECM Field Matrix II", "Provides 66% planetary ECM detection capability.", "advanced_detection_grid", "ECM Detection", 0.66),
  makeUpgrade("ECM Field Matrix III", "Provides 99% planetary ECM detection capability.", "advanced_detection_grid", "ECM Detection", 0.99),
  makeUpgrade("Empire Defense Control Matrix I", "Increases overall empire defense numbers by 10%.", "planetary_fortress_network", "Empire Defense", 0.10),
  makeUpgrade("Tax Office I", "Increases VRIND income by 5% per hour.", "taxation_doctrine", "VRIND Income", 0.05),
  makeUpgrade("Tax Office II", "Increases VRIND income by 10% per hour.", "taxation_doctrine", "VRIND Income", 0.10),
  makeUpgrade("Tax Office III", "Increases VRIND income by 15% per hour.", "taxation_doctrine", "VRIND Income", 0.15),
  makeUpgrade("TAX EVASION I", "Completely removes Global Market tax.", "galactic_trade_manipulation_ai", "Global Market Tax", -1),
  makeUpgrade("0 COMM FEE", "Removes all Global Comms fees.", "quantum_entanglement_command_matrix", "Global Comms Fee", -1),
  makeUpgrade("Alliance Bonus I", "Provides an alliance attack bonus when striking the same enemy.", "war_council", "Alliance Attack", 0.05),
  makeUpgrade("Alliance Bonus II", "Further increases the alliance attack bonus when striking the same enemy.", "war_council", "Alliance Attack", 0.10),
  makeUpgrade("Secured Fleet Network I", "Improves protection against hostile scouting.", "empire_data_encryption", "Scout Information Protection", 0.25),
  makeUpgrade("Secured Fleet Network II", "Further improves protection against hostile scouting.", "empire_data_encryption", "Scout Information Protection", 0.50),
  makeUpgrade("Anti Spy Network", "Detects hostile spies.", "counter_espionage", "Spy Detection", 0.25),
  makeUpgrade("Critical Spy Observation", "Hinders hostile spies from reporting complete information.", "counter_espionage", "Spy Disruption", 0.25),
  makeUpgrade("Capture and Interrogate", "Captures spies and reveals their origin.", "counter_espionage", "Spy Capture", 0.25),
  makeUpgrade("Entropy Single Shot", "Entropy Cannon bypasses Hull Armor and Shields 25% of the time.", "entropy_cannon", "Defense Bypass", 0.25),
  makeUpgrade("Entropy Multi Shot", "Entropy Cannon bypasses Hull Armor and Shields 50% of the time.", "entropy_cannon", "Defense Bypass", 0.50),
  makeUpgrade("Vampiric Field Generator Single Target", "Protects a designated capital ship in the surrounding fleet.", "vampiric_field_generator", "Capital Ship Protection", 0.25),
  makeUpgrade("Vampiric Field Generator Area", "Protects the surrounding capital-ship fleet area.", "vampiric_field_generator", "Fleet Area Protection", 0.25),
  makeUpgrade("Entropy Cascade", "Escalates entropy weaponry into a cascading destructive system.", "entropic_cascade_reactor", "Entropy Cascade", 0.25),
  makeUpgrade("Resonance Drain", "Expands vampiric energy transfer into resonance drain.", "vampiric_resonance_core", "Resonance Drain", 0.25),
  makeUpgrade("Phase Transit", "Allows controlled phase transit through forbidden architecture.", "quantum_phase_lattice", "Phase Transit", 0.25),
  makeUpgrade("Null Signature", "Suppresses detectable signatures through quantum interference.", "quantum_nullification_field", "Detection Suppression", 0.25),
  makeUpgrade("Singularity Cannon", "Compresses entropy effects into a singularity-scale weapon.", "entropy_singularity_engine", "Singularity Weapon", 0.25),
  makeUpgrade("Singularity Shield", "Creates singularity-scale defensive energy drain.", "vampiric_singularity_matrix", "Singularity Defense", 0.25),
  makeUpgrade("Permanent Phase Architecture", "Permanent phase architecture for a capital ship; it is not permanently undetectable.", "phase_singularity_drive", "Phase Architecture", 0.25),
  makeUpgrade("Detection Collapse", "Creates a severe detection-collapse effect for the Null Star support ship.", "quantum_null_matrix", "Detection Collapse", 0.25),

  // Economy and Resources — research nodes unlock these purchases.
  makeUpgrade("Planet Mining I", "Increases Ferrite-Titanium production to 15% above its current base.", "mining_resource_generation", "Ferrite Production", 0.15),
  makeUpgrade("Planet Mining II", "Increases Ferrite-Titanium production to 20% above its current base.", "mining_resource_generation", "Ferrite Production", 0.20),
  makeUpgrade("Planet Mining III", "Increases Ferrite-Titanium production to 25% above its current base.", "mining_resource_generation", "Ferrite Production", 0.25),
  makeUpgrade("Solar Energy Farm I", "Increases Energy production to 15% above its current base.", "mining_resource_generation", "Energy Production", 0.15),
  makeUpgrade("Solar Energy Farm II", "Increases Energy production to 20% above its current base.", "mining_resource_generation", "Energy Production", 0.20),
  makeUpgrade("Core Mining I", "Adds 5% to Ferrite-Titanium and Berentium production.", "sub_surface_mining", "Mining Production", 0.05),
  makeUpgrade("Core Mining II", "Adds 10% to Ferrite-Titanium and Berentium production.", "sub_surface_mining", "Mining Production", 0.10),
  makeUpgrade("Core Mining III", "Adds 20% to Ferrite-Titanium and Berentium production.", "sub_surface_mining", "Mining Production", 0.20),
  makeUpgrade("Core Mining IV", "Adds 25% to Ferrite-Titanium and Berentium production.", "sub_surface_mining", "Mining Production", 0.25),
  makeUpgrade("ADV ENERGY COLLECTION I", "Improves the empire's energy collection grid.", "energy_collection_grid", "Energy Production", 0.25),
  makeUpgrade("Orbital Miners I", "Begins orbital mining operations.", "orbit_mining", "Orbital Mining", 0.10),
  makeUpgrade("Orbital Miners II", "Expands orbital mining operations.", "orbit_mining", "Orbital Mining", 0.20),
  makeUpgrade("Deep Core Syphon I", "Adds 25% to Ferrite-Titanium and Berentium production.", "deep_core_extraction", "Deep Core Production", 0.25),
  makeUpgrade("Deep Core Syphon II", "Adds 35% to Ferrite-Titanium and Berentium production.", "deep_core_extraction", "Deep Core Production", 0.35),
  makeUpgrade("Deep Core Syphon III", "Adds 45% to Ferrite-Titanium and Berentium production.", "deep_core_extraction", "Deep Core Production", 0.45),
  makeUpgrade("ADV ENERGY COLLECTION II", "Further increases planetary solar energy collection.", "planetary_solar_harness", "Energy Production", 0.75),
  makeUpgrade("Orbital Miners III", "Triples Ferrite production and doubles Berentium production from automated orbital mining.", "intra_system_automated_mining", "Automated Mining", 2.00),
  makeUpgrade("ADV ENERGY COLLECTION III", "Adds a large orbital reflector energy bonus.", "orbit_solar_reflector", "Energy Production", 0.75),
  makeUpgrade("System Miners II", "Expands automated system-mining logistics capacity.", "intra_system_freighter_capacity", "System Mining Capacity", 0.25),
  makeUpgrade("Plasma Extraction I", "Adds 50% to all resource production.", "core_plasma_excavation", "All Resource Production", 0.50),
  makeUpgrade("Plasma Extraction II", "Adds another 50% to all resource production.", "core_plasma_excavation", "All Resource Production", 0.50),
  makeUpgrade("ADV ENERGY CONNECTION IV", "Adds a very large energy-production increase.", "orbital_energy_relay", "Energy Production", 1.50),
  makeUpgrade("Cargo Rails I", "Doubles Ferrite-Titanium and Berentium production.", "orbit_cargo_rails", "Bulk Mining Production", 1.00),
  makeUpgrade("Asteroid Hostler", "Increases Ferrite-Titanium, Berentium, and Aetherium Crystal production by 50%.", "asteroid_harpooning", "Asteroid Production", 0.50),
  makeUpgrade("Debris Scoop I", "Adds 25% to non-energy resource production.", "orbital_slag_production", "Slag Production", 0.25),
  makeUpgrade("Debris Scoop II", "Adds 35% to non-energy resource production.", "orbital_slag_production", "Slag Production", 0.35),
  makeUpgrade("Gravity Furnace I", "Adds 10% to non-energy resource production.", "gravimetric_core_harvesting", "Gravimetric Production", 0.10),
  makeUpgrade("Gravity Furnace II", "Adds 15% to non-energy resource production.", "gravimetric_core_harvesting", "Gravimetric Production", 0.15),
  makeUpgrade("Advanced Sling Mining I", "Adds 15% to non-energy resource production.", "mass_driver_sling", "Sling Mining Production", 0.15),
  makeUpgrade("Advanced Sling Mining II", "Adds 25% to non-energy resource production.", "mass_driver_sling", "Sling Mining Production", 0.25),
  makeUpgrade("Laser Ablator I", "Doubles Ferrite-Titanium, Berentium, and Aetherium Crystal production.", "laser_ablation_mining", "Laser Mining Production", 1.00),
  makeUpgrade("Zero G Refinery I", "Enables conversion of Ferrite-Titanium into Berentium at 5:1.", "zero_g_centrifugal_refinery", "Refinery Conversion", 0),
  makeUpgrade("Solar Energy Conversion I", "Improves Energy-to-Aetherium conversion to 100 Energy for 1 Aetherium Crystal.", "stellar_corona_skimming", "Energy Conversion", 0),
  makeUpgrade("ADV ENERGY COLLECTION VI", "Triples the already advanced zero-point energy collection output.", "zero_point_extraction", "Energy Production", 2.00),
];

const byId = new Map(EMPIRE_UPGRADES.map((u) => [u.id, u]));
export const getEmpireUpgrade = (id) => byId.get(id);
export function isEmpireUpgradeAvailable(upgrade, completedTechIds) { const set = completedTechIds instanceof Set ? completedTechIds : new Set(completedTechIds || []); return Boolean(upgrade && set.has(upgrade.gatingTechId)); }
export function getAvailableEmpireUpgrades(completedTechIds) { const set = completedTechIds instanceof Set ? completedTechIds : new Set(completedTechIds || []); return EMPIRE_UPGRADES.filter((u) => set.has(u.gatingTechId)); }
export function canPurchaseEmpireUpgrade(upgrade, purchasedUpgradeIds) { const purchased = purchasedUpgradeIds instanceof Set ? purchasedUpgradeIds : new Set(purchasedUpgradeIds || []); return Boolean(upgrade && !purchased.has(upgrade.id)); }
export function nextEmpireUpgradeTier(name, purchasedUpgradeIds) {
  const purchased = purchasedUpgradeIds instanceof Set ? purchasedUpgradeIds : new Set(purchasedUpgradeIds || []);
  return EMPIRE_UPGRADES.find((u) => u.name.startsWith(`${name} `) && !purchased.has(u.id)) || null;
}
