// Empire-wide upgrade definitions.
// Each Roman-numeral upgrade is a distinct one-time purchase unlocked by research.
const makeUpgrade = (name, description, gatingTechId, effectLabel, bonus, cost = { aetherium_crystal: 300, ferrite_titanium: 600, vrind: 800 }) => ({ id: name.toLowerCase().replace(/[^a-z0-9]+/g, "_"), name, description, gatingTechId, effectLabel, bonus, cost, maxLevel: 1 });
export const EMPIRE_UPGRADES = [
  makeUpgrade("Population Growth I", "Increases empire population growth.", "planetary_growth_economics", "Population Growth", 0.05), makeUpgrade("Population Growth II", "Further increases empire population growth.", "planetary_growth_matrix", "Population Growth", 0.05), makeUpgrade("Population Growth III", "Further increases empire population growth.", "imperial_networking", "Population Growth", 0.05),
  makeUpgrade("Income Upgrade I", "Strictly increases recurring VRIND income.", "economic_optimization", "VRIND Income", 0.05), makeUpgrade("Income Upgrade II", "Strictly increases recurring VRIND income.", "tachyon_communications", "VRIND Income", 0.05), makeUpgrade("Income Upgrade III", "Strictly increases recurring VRIND income.", "imperial_directives", "VRIND Income", 0.05),
  makeUpgrade("Resource Finder I", "Increases resources found during exploration.", "deep_space_survey_probe", "Resources Found", 0.05), makeUpgrade("Resource Finder II", "Further increases resources found during exploration.", "atmospheric_hazard_cartography", "Resources Found", 0.10), makeUpgrade("Resource Finder III", "Further increases resources found during exploration.", "atmospheric_hazard_cartography", "Resources Found", 0.15),
  makeUpgrade("Cost Reducer I", "Reduces Exploration Ship energy cost by 5%.", "anomaly_analysis_algorithms", "Exploration Energy Cost", -0.05), makeUpgrade("Cost Reducer II", "Reduces Exploration Ship energy cost by 10%.", "warp_lane_optimization", "Exploration Energy Cost", -0.10),
  makeUpgrade("Exploration Speed I", "Makes exploration 5% faster.", "tachyon_sensor_array", "Exploration Time", -0.05), makeUpgrade("Exploration Speed II", "Makes exploration 10% faster.", "relic_matrices", "Exploration Time", -0.10), makeUpgrade("Exploration Speed III", "Makes exploration 15% faster.", "warp_lane_optimization", "Exploration Time", -0.15), makeUpgrade("Exploration Speed IV", "Makes exploration 20% faster.", "fold_navigation", "Exploration Time", -0.20),
  makeUpgrade("ECM Field Matrix I", "Provides 33% planetary ECM detection capability.", "advanced_detection_grid", "ECM Detection", 0.33), makeUpgrade("ECM Field Matrix II", "Provides 66% planetary ECM detection capability.", "advanced_detection_grid", "ECM Detection", 0.66), makeUpgrade("ECM Field Matrix III", "Provides 99% planetary ECM detection capability.", "advanced_detection_grid", "ECM Detection", 0.99), makeUpgrade("Empire Defense Control Matrix I", "Increases overall empire defense numbers by 10%.", "planetary_fortress_network", "Empire Defense", 0.10),
  makeUpgrade("Tax Office I", "Increases VRIND income by 5% per hour.", "taxation_doctrine", "VRIND Income", 0.05), makeUpgrade("Tax Office II", "Increases VRIND income by 10% per hour.", "taxation_doctrine", "VRIND Income", 0.10), makeUpgrade("Tax Office III", "Increases VRIND income by 15% per hour.", "taxation_doctrine", "VRIND Income", 0.15), makeUpgrade("TAX EVASION I", "Completely removes Global Market tax.", "galactic_trade_manipulation_ai", "Global Market Tax", -1), makeUpgrade("0 COMM FEE", "Removes all Global Comms fees.", "quantum_entanglement_command_matrix", "Global Comms Fee", -1),
  makeUpgrade("Alliance Bonus I", "Provides an alliance attack bonus when striking the same enemy.", "war_council", "Alliance Attack", 0.05), makeUpgrade("Alliance Bonus II", "Further increases the alliance attack bonus when striking the same enemy.", "war_council", "Alliance Attack", 0.10), makeUpgrade("Secured Fleet Network I", "Improves protection against hostile scouting.", "empire_data_encryption", "Scout Information Protection", 0.25), makeUpgrade("Secured Fleet Network II", "Further improves protection against hostile scouting.", "empire_data_encryption", "Scout Information Protection", 0.50), makeUpgrade("Anti Spy Network", "Detects hostile spies.", "counter_espionage", "Spy Detection", 0.25), makeUpgrade("Critical Spy Observation", "Hinders hostile spies from reporting complete information.", "counter_espionage", "Spy Disruption", 0.25), makeUpgrade("Capture and Interrogate", "Captures spies and reveals their origin.", "counter_espionage", "Spy Capture", 0.25),
  makeUpgrade("Entropy Single Shot", "Entropy Cannon bypasses Hull Armor and Shields 25% of the time.", "entropy_cannon", "Defense Bypass", 0.25), makeUpgrade("Entropy Multi Shot", "Entropy Cannon bypasses Hull Armor and Shields 50% of the time.", "entropy_cannon", "Defense Bypass", 0.50), makeUpgrade("Vampiric Field Generator Single Target", "Protects a designated capital ship in the surrounding fleet.", "vampiric_field_generator", "Capital Ship Protection", 0.25), makeUpgrade("Vampiric Field Generator Area", "Protects the surrounding capital-ship fleet area.", "vampiric_field_generator", "Fleet Area Protection", 0.25), makeUpgrade("Entropy Cascade", "Escalates entropy weaponry into a cascading destructive system.", "entropic_cascade_reactor", "Entropy Cascade", 0.25), makeUpgrade("Resonance Drain", "Expands vampiric energy transfer into resonance drain.", "vampiric_resonance_core", "Resonance Drain", 0.25), makeUpgrade("Phase Transit", "Allows controlled phase transit through forbidden architecture.", "quantum_phase_lattice", "Phase Transit", 0.25), makeUpgrade("Null Signature", "Suppresses detectable signatures through quantum interference.", "quantum_nullification_field", "Detection Suppression", 0.25), makeUpgrade("Singularity Cannon", "Compresses entropy effects into a singularity-scale weapon.", "entropy_singularity_engine", "Singularity Weapon", 0.25), makeUpgrade("Singularity Shield", "Creates singularity-scale defensive energy drain.", "vampiric_singularity_matrix", "Singularity Defense", 0.25), makeUpgrade("Permanent Phase Architecture", "Permanent phase architecture for a capital ship; it is not permanently undetectable.", "phase_singularity_drive", "Phase Architecture", 0.25), makeUpgrade("Detection Collapse", "Creates a severe detection-collapse effect for the Null Star support ship.", "quantum_null_matrix", "Detection Collapse", 0.25),
];
const byId = new Map(EMPIRE_UPGRADES.map((u) => [u.id, u])); export const getEmpireUpgrade = (id) => byId.get(id);
export function isEmpireUpgradeAvailable(upgrade, completedTechIds) { const set = completedTechIds instanceof Set ? completedTechIds : new Set(completedTechIds || []); return Boolean(upgrade && set.has(upgrade.gatingTechId)); }
export function getAvailableEmpireUpgrades(completedTechIds) { const set = completedTechIds instanceof Set ? completedTechIds : new Set(completedTechIds || []); return EMPIRE_UPGRADES.filter((u) => set.has(u.gatingTechId)); }
export function canPurchaseEmpireUpgrade(upgrade, purchasedUpgradeIds) { const purchased = purchasedUpgradeIds instanceof Set ? purchasedUpgradeIds : new Set(purchasedUpgradeIds || []); return Boolean(upgrade && !purchased.has(upgrade.id)); }
// Backward-compatible helper for older Upgrade Page callers. Roman-numeral entries are one-time purchases, so this returns the next unpurchased upgrade in a same-name series.
export function nextEmpireUpgradeTier(name, purchasedUpgradeIds) {
  const purchased = purchasedUpgradeIds instanceof Set ? purchasedUpgradeIds : new Set(purchasedUpgradeIds || []);
  return EMPIRE_UPGRADES.find((u) => u.name.startsWith(`${name} `) && !purchased.has(u.id)) || null;
}
