// Galactic Dominion — canonical technology tree dataset.
// Research nodes live here; Roman numeral entries are Upgrade Page purchases.
// Hidden restricted trees are only exposed when their explicit gate is met.

export const CATEGORIES = {
  Defense: { icon: "Shield", color: "text-red-300" },
  "Economy and Resources": { icon: "Coins", color: "text-yellow-300" },
  "Fleet Research": { icon: "Rocket", color: "text-cyan-300" },
  Exploration: { icon: "Radar", color: "text-emerald-300" },
  "Empire Governance": { icon: "Crown", color: "text-violet-300" },
};

export const CATEGORY_ORDER = ["Defense", "Economy and Resources", "Fleet Research", "Exploration", "Empire Governance"];

const u = (name) => ({ upgrades: [name] });

export const TECH_TREE = [
  { id: "defense_command", name: "Defense Command", description: "Establishes the empire's formal planetary and fleet defense doctrine.", category: "Defense", icon: "Shield", tier: 1, researchTurns: 1, prerequisites: [], isPrimary: true },
  { id: "planetary_defense_architecture", name: "Planetary Defense Architecture", description: "Creates the framework for layered planetary defense installations.", category: "Defense", tier: 2, researchTurns: 2, prerequisites: ["defense_command"], isPrimary: true, unlocks: { units: ["bunker", "pdg"] } },
  { id: "fleet_defense_doctrine", name: "Fleet Defense Doctrine", description: "Formalizes defensive fleet formations and capital protection doctrine.", category: "Defense", tier: 2, researchTurns: 2, prerequisites: ["defense_command"] },
  { id: "early_warning_network", name: "Early Warning Network", description: "Links planetary sensors into an integrated hostile-fleet warning system.", category: "Defense", tier: 3, researchTurns: 3, prerequisites: ["planetary_defense_architecture"] },
  { id: "heavy_battery_systems", name: "Heavy Battery Systems", description: "Unlocks massive planetary battery emplacements designed to engage large warships.", category: "Defense", tier: 3, researchTurns: 3, prerequisites: ["planetary_defense_architecture"], isPrimary: true, unlocks: { units: ["heavy_battery"] } },
  { id: "point_defense_grid", name: "Point Defense Grid", description: "Layered planetary point-defense weapons protect installations from incoming craft and ordnance.", category: "Defense", tier: 3, researchTurns: 3, prerequisites: ["planetary_defense_architecture"], isPrimary: true, unlocks: { units: ["pdg"] } },
  { id: "shield_coordination", name: "Shield Coordination", description: "Coordinates defensive shield systems across installations and fleet formations.", category: "Defense", tier: 3, researchTurns: 3, prerequisites: ["fleet_defense_doctrine"] },
  { id: "ecm_detection_architecture", name: "ECM Detection Architecture", description: "Creates the detection framework used to resist stealth and electronic concealment.", category: "Defense", tier: 4, researchTurns: 4, prerequisites: ["early_warning_network"] },
  { id: "fortress_command", name: "Fortress Command", description: "Integrates planetary defenses into a unified command structure.", category: "Defense", tier: 4, researchTurns: 4, prerequisites: ["heavy_battery_systems", "shield_coordination"], unlocks: { buildings: ["fortress_command"] } },
  { id: "advanced_detection_grid", name: "Advanced Detection Grid", description: "Expands the empire's ability to detect concealed fleets.", category: "Defense", tier: 5, researchTurns: 5, prerequisites: ["ecm_detection_architecture"], unlocks: u("ECM Field Matrix I") },
  { id: "planetary_fortress_network", name: "Planetary Fortress Network", description: "The final conventional defense architecture.", category: "Defense", tier: 6, researchTurns: 6, prerequisites: ["fortress_command", "advanced_detection_grid"], isPrimary: true, unlocks: u("Empire Defense Control Matrix I") },

  { id: "resource_administration", name: "Resource Administration", description: "Establishes centralized management of imperial production and resources.", category: "Economy and Resources", tier: 1, researchTurns: 1, prerequisites: [], isPrimary: true },
  { id: "industrial_expansion", name: "Industrial Expansion", description: "Expands planetary industry and production capacity.", category: "Economy and Resources", tier: 2, researchTurns: 2, prerequisites: ["resource_administration"] },
  { id: "resource_extraction", name: "Advanced Resource Extraction", description: "Improves extraction of strategic resources.", category: "Economy and Resources", tier: 2, researchTurns: 2, prerequisites: ["resource_administration"] },
  { id: "vrind_economy", name: "VRIND Economic Systems", description: "Formalizes the empire's VRIND economy and revenue infrastructure.", category: "Economy and Resources", tier: 3, researchTurns: 3, prerequisites: ["resource_administration"] },
  { id: "planetary_growth_economics", name: "Planetary Growth Economics", description: "Aligns population growth with long-term economic output.", category: "Economy and Resources", tier: 3, researchTurns: 3, prerequisites: ["industrial_expansion"], unlocks: u("Population Growth I") },
  { id: "advanced_mining_network", name: "Advanced Mining Network", description: "Coordinates extraction operations across planetary and orbital deposits.", category: "Economy and Resources", tier: 3, researchTurns: 3, prerequisites: ["resource_extraction"] },
  { id: "galactic_trade", name: "Galactic Trade", description: "Opens larger-scale interplanetary and galactic market operations.", category: "Economy and Resources", tier: 4, researchTurns: 4, prerequisites: ["vrind_economy", "advanced_mining_network"] },
  { id: "economic_optimization", name: "Economic Optimization", description: "Increases recurring VRIND income.", category: "Economy and Resources", tier: 4, researchTurns: 4, prerequisites: ["vrind_economy"], unlocks: u("Income Upgrade I") },
  { id: "trade_manipulation", name: "Trade Manipulation", description: "Advanced market systems influence taxation and trade flows.", category: "Economy and Resources", tier: 5, researchTurns: 5, prerequisites: ["galactic_trade", "economic_optimization"] },
  { id: "resource_dominance", name: "Resource Dominance", description: "A mature economic network optimized for sustained imperial expansion.", category: "Economy and Resources", tier: 6, researchTurns: 6, prerequisites: ["trade_manipulation", "planetary_growth_economics"], isPrimary: true, unlocks: u("Tax Office I") },

  { id: "fleet_foundation", name: "Fleet Foundation", description: "Establishes the research doctrine for military spacecraft and fleet operations.", category: "Fleet Research", tier: 1, researchTurns: 1, prerequisites: [], isPrimary: true },
  { id: "standard_hull_framing", name: "Standard Hull Framing", description: "Creates standardized hull architecture used by fleet yards.", category: "Fleet Research", tier: 2, researchTurns: 2, prerequisites: ["fleet_foundation"], isPrimary: true, unlocks: { units: ["scout_ship", "medium_frigate"] } },
  { id: "jump_drive_attunement", name: "Jump Drive Attunement", description: "Improves jump calculations and arrival positioning.", category: "Fleet Research", tier: 2, researchTurns: 2, prerequisites: ["fleet_foundation"] },
  { id: "frigate_design", name: "Frigate Design", description: "Develops specialized frigate hulls.", category: "Fleet Research", tier: 3, researchTurns: 3, prerequisites: ["standard_hull_framing"], isPrimary: true, unlocks: { units: ["medium_frigate", "heavy_frigate"] } },
  { id: "destroyer_design", name: "Destroyer Design", description: "Develops heavier escort and line-combat hulls.", category: "Fleet Research", tier: 3, researchTurns: 3, prerequisites: ["standard_hull_framing"], isPrimary: true, unlocks: { units: ["destroyer", "heavy_super_destroyer"] } },
  { id: "quantum_computing", name: "Quantum Computing", description: "Advanced computation accelerates research.", category: "Fleet Research", tier: 3, researchTurns: 3, prerequisites: ["jump_drive_attunement"], unlocks: { abilities: ["research_speed"] } },
  { id: "cruiser_hull", name: "Cruiser Hull Architecture", description: "Creates cruiser-scale combat architecture.", category: "Fleet Research", tier: 4, researchTurns: 4, prerequisites: ["frigate_design", "destroyer_design"], isPrimary: true, unlocks: { units: ["light_cruiser", "medium_cruiser", "heavy_cruiser"] } },
  { id: "carrier_architecture", name: "Carrier Architecture", description: "Develops dedicated carrier systems.", category: "Fleet Research", tier: 4, researchTurns: 4, prerequisites: ["cruiser_hull"], isPrimary: true, unlocks: { units: ["carrier", "drone_carrier"] } },
  { id: "capital_hull_engineering", name: "Capital Hull Engineering", description: "Allows construction of battleship, dreadnought and battlecruiser-scale hulls.", category: "Fleet Research", tier: 5, researchTurns: 5, prerequisites: ["cruiser_hull"], isPrimary: true, unlocks: { units: ["battleship", "battlecruiser", "dreadnought"] } },
  { id: "fleet_command_network", name: "Fleet Command Network", description: "Links fleets into a coordinated battlespace network.", category: "Fleet Research", tier: 5, researchTurns: 5, prerequisites: ["quantum_computing", "capital_hull_engineering"] },
  { id: "advanced_fleet_architecture", name: "Advanced Fleet Architecture", description: "Final conventional fleet research before specialized technologies.", category: "Fleet Research", tier: 6, researchTurns: 6, prerequisites: ["carrier_architecture", "capital_hull_engineering", "fleet_command_network"], isPrimary: true, unlocks: { units: ["titan", "exploration_command_ship"] } },

  { id: "long_range_sensors", name: "Long Range Sensors", description: "Detect and analyze distant regions of space.", category: "Exploration", tier: 1, researchTurns: 1, prerequisites: [], isPrimary: true, unlocks: { units: ["pathfinder_exploration_vessel"] } },
  { id: "aero_probe_launcher", name: "Aero-Probe Launcher", description: "Launches autonomous probes into hazardous regions.", category: "Exploration", tier: 1, researchTurns: 1, prerequisites: [], isPrimary: true, unlocks: { units: ["pathfinder_exploration_vessel"] } },
  { id: "sub_light_mapping", name: "Sub Light Mapping", description: "Maps local space without full warp transit.", category: "Exploration", tier: 1, researchTurns: 1, prerequisites: [], isPrimary: true, unlocks: { units: ["pathfinder_exploration_vessel"] } },
  { id: "tachyon_sensor_array", name: "Tachyon Sensor Array", description: "Extends sensor range.", category: "Exploration", tier: 2, researchTurns: 2, prerequisites: ["long_range_sensors"], unlocks: u("Exploration Speed I") },
  { id: "deep_space_survey_probe", name: "Deep Space Survey Probe", description: "Deploys durable probes for long-duration resource surveys.", category: "Exploration", tier: 2, researchTurns: 2, prerequisites: ["aero_probe_launcher"], unlocks: u("Resource Finder I") },
  { id: "anomaly_analysis_algorithms", name: "Anomaly Analysis Algorithms", description: "Identifies unusual signals and ancient sites.", category: "Exploration", tier: 2, researchTurns: 2, prerequisites: ["sub_light_mapping"], unlocks: u("Cost Reducer I") },
  { id: "relic_matrices", name: "Relic Matrices", description: "Interprets ancient structures and signals.", category: "Exploration", tier: 3, researchTurns: 3, prerequisites: ["tachyon_sensor_array"] },
  { id: "atmospheric_hazard_cartography", name: "Atmospheric Hazard Cartography", description: "Maps hazardous environments and improves ancient lost technology discovery.", category: "Exploration", tier: 3, researchTurns: 3, prerequisites: ["deep_space_survey_probe"], unlocks: u("Resource Finder II") },
  { id: "warp_lane_optimization", name: "Warp Lane Optimization", description: "Optimizes exploration routes and reduces travel time.", category: "Exploration", tier: 3, researchTurns: 3, prerequisites: ["anomaly_analysis_algorithms"], unlocks: u("Cost Reducer II") },
  { id: "study_ancient_languages", name: "Study Ancient Languages", description: "Deciphers ancient language systems and permits communication with visiting alien traders once the Travel Trade Center exists.", category: "Exploration", tier: 4, researchTurns: 4, prerequisites: ["relic_matrices"] },
  { id: "subspace_beacon_network", name: "Subspace Beacon Network", description: "Creates navigational beacons for deeper exploration missions.", category: "Exploration", tier: 4, researchTurns: 4, prerequisites: ["relic_matrices"], unlocks: { units: ["wayfinder_exploration_vessel"] } },
  { id: "fold_navigation", name: "Fold Navigation", description: "Completes the conventional exploration program.", category: "Exploration", tier: 5, researchTurns: 5, prerequisites: ["warp_lane_optimization"], unlocks: u("Exploration Speed IV") },
  { id: "relic_adhesion_matrix_ai", name: "Relic Adhesion Matrix AI", description: "A dangerous AI that reconstructs and integrates ancient technology. This is one half of the gate to Blacklisted Alien Technology.", category: "Exploration", tier: 6, researchTurns: 6, prerequisites: ["subspace_beacon_network", "study_ancient_languages"], isPrimary: true, unlockTags: ["blacklisted_gate"] },

  { id: "centralized_administration", name: "Centralized Administration", description: "Concentrates imperial administration into a unified governing structure.", category: "Empire Governance", tier: 1, researchTurns: 1, prerequisites: [], isPrimary: true },
  { id: "sub_space_relays", name: "Sub-space Relays", description: "Establishes the communication backbone for the empire.", category: "Empire Governance", tier: 1, researchTurns: 1, prerequisites: [], isPrimary: true, unlocks: { abilities: ["global_comms"] } },
  { id: "standardized_empire_codes", name: "Standardized Empire Codes", description: "Creates common legal and administrative standards.", category: "Empire Governance", tier: 1, researchTurns: 1, prerequisites: [], isPrimary: true, unlocks: { abilities: ["political_tab"] } },
  { id: "planetary_growth_matrix", name: "Planetary Growth Matrix", description: "Coordinates planetary population and development policy.", category: "Empire Governance", tier: 2, researchTurns: 2, prerequisites: ["centralized_administration"], unlocks: u("Population Growth II") },
  { id: "tachyon_communications", name: "Tachyon Communications", description: "High-speed communications increase VRIND income.", category: "Empire Governance", tier: 2, researchTurns: 2, prerequisites: ["sub_space_relays"], unlocks: u("Income Upgrade II") },
  { id: "imperial_directives", name: "Imperial Directives", description: "Central directives increase VRIND income.", category: "Empire Governance", tier: 2, researchTurns: 2, prerequisites: ["standardized_empire_codes"], unlocks: u("Income Upgrade III") },
  { id: "imperial_networking", name: "Imperial Networking", description: "Links administrative centers across the empire.", category: "Empire Governance", tier: 3, researchTurns: 3, prerequisites: ["planetary_growth_matrix"], unlocks: u("Population Growth III") },
  { id: "quantum_entanglement_command_matrix", name: "Quantum Entanglement Command Matrix", description: "Instant command and communication across imperial distances.", category: "Empire Governance", tier: 3, researchTurns: 3, prerequisites: ["tachyon_communications"], unlocks: { abilities: ["zero_comm_fee"] } },
  { id: "diplomatic_decree", name: "Diplomatic Decree", description: "Creates the legal authority for formal alliances.", category: "Empire Governance", tier: 3, researchTurns: 3, prerequisites: ["imperial_directives"], unlocks: { abilities: ["alliance_creation"] } },
  { id: "empire_data_encryption", name: "Empire Data Encryption", description: "Protects imperial intelligence from hostile reconnaissance.", category: "Empire Governance", tier: 4, researchTurns: 4, prerequisites: ["imperial_networking"], unlocks: u("Secured Fleet Network I") },
  { id: "centralized_command_matrix", name: "Centralized Command Matrix", description: "Unifies defensive command.", category: "Empire Governance", tier: 4, researchTurns: 4, prerequisites: ["imperial_networking"], unlocks: u("Empire Defense Control Matrix I") },
  { id: "sub_space_data_networks", name: "Sub-space Data Networks", description: "Creates the next generation of secure imperial data routing.", category: "Empire Governance", tier: 4, researchTurns: 4, prerequisites: ["imperial_networking"] },
  { id: "galactic_trade_manipulation_ai", name: "Galactic Trade Manipulation AI", description: "An economic AI capable of manipulating market taxation systems.", category: "Empire Governance", tier: 4, researchTurns: 4, prerequisites: ["quantum_entanglement_command_matrix"], unlocks: u("TAX EVASION I") },
  { id: "travel_trade_ambassador", name: "Travel Trade Ambassador", description: "Establishes the diplomatic authority for an Alien Travel Trade Center.", category: "Empire Governance", tier: 4, researchTurns: 4, prerequisites: ["quantum_entanglement_command_matrix"], unlocks: { buildings: ["alien_travel_trade_center"] } },
  { id: "empire_control_overlord", name: "Empire Control OVERLORD", description: "Emergency imperial authority. This is the second half of the Blacklisted Alien Technology gate.", category: "Empire Governance", tier: 5, researchTurns: 4, prerequisites: ["quantum_entanglement_command_matrix"], isPrimary: true, unlocks: { abilities: ["martial_law"] }, unlockTags: ["blacklisted_gate"] },
  { id: "espionage", name: "Espionage", description: "Unlocks the Espionage operations system.", category: "Empire Governance", tier: 4, researchTurns: 4, prerequisites: ["diplomatic_decree"], unlocks: { abilities: ["espionage"] } },
  { id: "counter_espionage", name: "Counter Espionage", description: "Develops systems for detecting, hindering and capturing hostile spies.", category: "Empire Governance", tier: 4, researchTurns: 4, prerequisites: ["diplomatic_decree"], unlocks: u("Anti Spy Network") },
  { id: "war_council", name: "War Council", description: "Formalizes allied military coordination against common enemies.", category: "Empire Governance", tier: 4, researchTurns: 4, prerequisites: ["diplomatic_decree"], unlocks: u("Alliance Bonus I") },
  { id: "taxation_doctrine", name: "Taxation Doctrine", description: "Creates formal imperial taxation policy.", category: "Empire Governance", tier: 4, researchTurns: 4, prerequisites: ["diplomatic_decree"], unlocks: u("Tax Office I") },

  // Hidden: Blacklisted Alien Technology. This tree must never be available
  // from normal category navigation until BOTH gate technologies are complete.
  { id: "blacklisted_alien_technology", name: "Blacklisted Alien Technology", description: "Restricted ancient technology recovered through the Relic Adhesion Matrix AI and controlled through the Empire Control OVERLORD. Every technology in this tree carries catastrophic instability risk.", category: "Blacklisted Alien Technology", tier: 0, researchTurns: 0, prerequisites: { all: ["relic_adhesion_matrix_ai", "empire_control_overlord"] }, hidden: false, isGate: true },
  { id: "void_siphon_engine", name: "Void Siphon Engine", description: "A blacklisted energy system that extracts usable power from hostile void phenomena.", category: "Blacklisted Alien Technology", tier: 1, researchTurns: 6, prerequisites: ["blacklisted_alien_technology"], hidden: true, unlockTags: ["blacklisted", "unstable"] },
  { id: "quantum_core", name: "Quantum Core", description: "A prohibited quantum-energy core capable of supporting impossible hull architectures.", category: "Blacklisted Alien Technology", tier: 1, researchTurns: 6, prerequisites: ["blacklisted_alien_technology"], hidden: true, unlockTags: ["blacklisted", "unstable"] },
  { id: "entropy_cannon", name: "Entropy Cannon", description: "A weapon that destabilizes matter and can bypass conventional defenses.", category: "Blacklisted Alien Technology", tier: 2, researchTurns: 7, prerequisites: ["void_siphon_engine"], hidden: true, unlocks: { upgrades: ["Entropy Single Shot", "Entropy Multi Shot"] }, unlockTags: ["blacklisted", "unstable"] },
  { id: "vampiric_field_generator", name: "Vampiric Field Generator", description: "A prohibited field that transfers defensive energy between designated vessels.", category: "Blacklisted Alien Technology", tier: 2, researchTurns: 7, prerequisites: ["quantum_core"], hidden: true, unlocks: { upgrades: ["Vampiric Field Generator Single Target", "Vampiric Field Generator Area"], units: ["vampiric_shield_ship"] }, unlockTags: ["blacklisted", "unstable"] },
  { id: "phasing_hull_matrix", name: "Phasing Hull Matrix", description: "A forbidden hull architecture that allows a vessel to bypass every known defense and detection system.", category: "Blacklisted Alien Technology", tier: 2, researchTurns: 7, prerequisites: ["quantum_core"], hidden: true, unlocks: { units: ["phase_scout"] }, unlockTags: ["blacklisted", "unstable", "zero_detection"] },
  { id: "entropic_cascade_reactor", name: "Entropic Cascade Reactor", description: "Escalates entropy weaponry into a cascading destructive system.", category: "Blacklisted Alien Technology", tier: 3, researchTurns: 8, prerequisites: ["entropy_cannon"], hidden: true, unlocks: { upgrades: ["Entropy Cascade"] , units: ["entropy_destroyer"] }, unlockTags: ["blacklisted", "unstable"] },
  { id: "vampiric_resonance_core", name: "Vampiric Resonance Core", description: "Expands vampiric energy transfer into a resonance weapon system.", category: "Blacklisted Alien Technology", tier: 3, researchTurns: 8, prerequisites: ["vampiric_field_generator"], hidden: true, unlocks: { upgrades: ["Resonance Drain"], units: ["vampiric_guardian"] }, unlockTags: ["blacklisted", "unstable"] },
  { id: "quantum_phase_lattice", name: "Quantum Phase Lattice", description: "Extends phasing architecture into controlled phase transit.", category: "Blacklisted Alien Technology", tier: 3, researchTurns: 8, prerequisites: ["phasing_hull_matrix"], hidden: true, unlocks: { upgrades: ["Phase Transit"], units: ["phase_interceptor"] }, unlockTags: ["blacklisted", "unstable"] },
  { id: "quantum_nullification_field", name: "Quantum Nullification Field", description: "Suppresses detectable signatures through forbidden quantum interference.", category: "Blacklisted Alien Technology", tier: 3, researchTurns: 8, prerequisites: ["quantum_core"], hidden: true, unlocks: { upgrades: ["Null Signature"], units: ["nullifier_ship"] }, unlockTags: ["blacklisted", "unstable"] },
  { id: "entropy_singularity_engine", name: "Entropy Singularity Engine", description: "Compresses entropy effects into a singularity-scale weapon.", category: "Blacklisted Alien Technology", tier: 4, researchTurns: 10, prerequisites: ["entropic_cascade_reactor"], hidden: true, unlocks: { upgrades: ["Singularity Cannon"], units: ["entropy_reaper"] }, unlockTags: ["blacklisted", "unstable"] },
  { id: "vampiric_singularity_matrix", name: "Vampiric Singularity Matrix", description: "Creates a singularity-scale defensive energy drain.", category: "Blacklisted Alien Technology", tier: 4, researchTurns: 10, prerequisites: ["vampiric_resonance_core"], hidden: true, unlocks: { upgrades: ["Singularity Shield"], units: ["vampiric_leviathan"] }, unlockTags: ["blacklisted", "unstable"] },
  { id: "phase_singularity_drive", name: "Phase Singularity Drive", description: "Creates permanent phase architecture for a capital ship. It is not permanently undetectable.", category: "Blacklisted Alien Technology", tier: 4, researchTurns: 10, prerequisites: ["quantum_phase_lattice"], hidden: true, unlocks: { upgrades: ["Permanent Phase Architecture"], units: ["phase_dreadnought"] }, unlockTags: ["blacklisted", "unstable"] },
  { id: "quantum_null_matrix", name: "Quantum Null Matrix", description: "A final quantum-null architecture for a dedicated support vessel.", category: "Blacklisted Alien Technology", tier: 4, researchTurns: 10, prerequisites: ["quantum_nullification_field"], hidden: true, unlocks: { upgrades: ["Detection Collapse"], units: ["null_star"] }, unlockTags: ["blacklisted", "unstable"] },

  // Dedicated instability research: reduces catastrophic failure chance but
  // never reaches zero. These are intentionally separate from normal empire upgrades.
  { id: "blacklisted_instability_control", name: "Blacklisted Technology Instability Control", description: "Dedicated research reduces catastrophic failure probability for blacklisted systems, but can never reduce it to 0%.", category: "Blacklisted Alien Technology", tier: 5, researchTurns: 12, prerequisites: ["entropy_singularity_engine", "vampiric_singularity_matrix", "phase_singularity_drive", "quantum_null_matrix"], hidden: true, unlockTags: ["blacklisted", "instability_control"] },
];

export function normalizePrereqs(tech) {
  if (!tech) return { all: [], any: [] };
  if (Array.isArray(tech.prerequisites)) return { all: tech.prerequisites, any: [] };
  const p = tech.prerequisites || {};
  return { all: p.all || [], any: p.any || [] };
}

export function defaultResearchCost(tier) {
  const t = Math.max(1, Number(tier) || 1);
  return { research_points: 20 * (2 ** (t - 1)), vrind: 40 * (2 ** (t - 1)) };
}

export function getResearchCost(tech) { return tech?.researchCost || defaultResearchCost(tech?.tier); }
export function isPrimaryTech(tech) { return tech?.isPrimary === true || (!Object.prototype.hasOwnProperty.call(tech || {}, "isPrimary") && tech?.tier === 1); }
export function getUnlocks(tech) { return tech?.unlocks || {}; }